env_describe_full = {
    'Ant-v4': 'The task is a reinforcement learning problem where an agent controls a 3-dimensional quadruped robot consisting of a torso (free rotational body) with four legs attached to it, where each leg has two body parts. The action space consists of 8 continuous values, each between -1 and 1, representing the torque applied at one hinge joints: {{0: the rotor between the torso and back right hip, 1: the rotor between the back right two links, 2: the rotor between the torso and front left hip, 3: the rotor between the front left two links, 4: the rotor between the torso and front right hip, 5: the rotor between the front right two links, 6: the rotor between the torso and back left hip, 7: the rotor between the back left two links}}. The goal is to coordinate the four legs to move in the forward (right) direction by applying torque to the eight hinges connecting the two body parts of each leg and the torso (nine body parts and eight hinges).',

    'HalfCheetah-v4':'The task is a reinforcement learning problem where an agent controls a 2-dimensional robot consisting of 9 body parts and 8 joints connecting them (including two paws). The robot’s torso and head are fixed, and torque can only be applied to the other 6 joints over the front and back thighs (which connect to the torso), the shins (which connect to the thighs), and the feet (which connect to the shins). The action space consists of 6 continuous values, each between -1 and 1, representing the torque applied at one hinge joints: {{0: the back thigh rotor, 1: the back shin rotor, 2: the back foot rotor, 3: the front thigh rotor, 4: the front shin rotor, 5:the front foot rotor}}. The goal is to apply torque to the joints to make the robot run forward (right) as fast as possible, with a positive reward based on the distance moved forward and a negative reward for moving backward.',
    
    'Hopper-v4':'The task is a reinforcement learning problem where an agent controls a 2-dimensional one-legged figure consisting of four main body parts - the torso at the top, the thigh in the middle, the leg at the bottom, and a single foot on which the entire body rests. The action space consists of 3 continuous values, each between -1 and 1, representing the torque applied at one hinge joints: {{0: the thigh rotor, 1: the leg rotor, 2: the foot rotor}}. The goal is to make the robot that move in the forward (right) direction by applying torque to the three hinges that connect the four body parts.',
    
    'Humanoid-v4':'The task is a reinforcement learning problem where an agent controls a 3-dimensional bipedal robot that is designed to simulate a human. It has a torso (abdomen) with a pair of legs and arms, and a pair of tendons connecting the hips to the knees. The legs each consist of three body parts (thigh, shin, foot), and the arms consist of two body parts (upper arm, forearm). The action space consists of 17 continuous values, each between -0.4 and 0.4, representing the torque applied at one hinge joints: {{0: the hinge in the y-coordinate of the abdomen, 1: the hinge in the z-coordinate of the abdomen, 2: the hinge in the x-coordinate of the abdomen, 3: the rotor between torso/abdomen and the right hip (x-coordinate), 4: the rotor between torso/abdomen and the right hip (z-coordinate), 5: the rotor between torso/abdomen and the right hip (y-coordinate), 6: the rotor between the right hip/thigh and the right shin, 7: the rotor between torso/abdomen and the left hip (x-coordinate), 8: the rotor between torso/abdomen and the left hip (z-coordinate), 9: the rotor between torso/abdomen and the left hip (y-coordinate), 10: the rotor between the left hip/thigh and the left shin, 11: the rotor between the torso and right upper arm (coordinate -1), 12: the rotor between the torso and right upper arm (coordinate -2), 13: the rotor between the right upper arm and right lower arm, 14: the rotor between the torso and left upper arm (coordinate -1), 15: the rotor between the torso and left upper arm (coordinate -2), 16: the rotor between the left upper arm and left lower arm}}. The goal of the task is to walk forward as fast as possible without falling over.',
    
    'HumanoidStandup-v4':'The task is a reinforcement learning problem where an agent controls a 3-dimensional bipedal robot that is designed to simulate a human. It has a torso (abdomen) with a pair of legs and arms, and a pair of tendons connecting the hips to the knees. The legs each consist of three body parts (thigh, shin, foot), and the arms consist of two body parts (upper arm, forearm). The action space consists of 17 continuous values, each between -0.4 and 0.4, representing the torque applied at one hinge joints: {{0: the hinge in the y-coordinate of the abdomen, 1: the hinge in the z-coordinate of the abdomen, 2: the hinge in the x-coordinate of the abdomen, 3: the rotor between torso/abdomen and the right hip (x-coordinate), 4: the rotor between torso/abdomen and the right hip (z-coordinate), 5: the rotor between torso/abdomen and the right hip (y-coordinate), 6: the rotor between the right hip/thigh and the right shin, 7: the rotor between torso/abdomen and the left hip (x-coordinate), 8: the rotor between torso/abdomen and the left hip (z-coordinate), 9: the rotor between torso/abdomen and the left hip (y-coordinate), 10: the rotor between the left hip/thigh and the left shin, 11: the rotor between the torso and right upper arm (coordinate -1), 12: the rotor between the torso and right upper arm (coordinate -2), 13: the rotor between the right upper arm and right lower arm, 14: the rotor between the torso and left upper arm (coordinate -1), 15: the rotor between the torso and left upper arm (coordinate -2), 16: the rotor between the left upper arm and left lower arm}}. The goal of the task is to make the humanoid stand up and then keep it standing by applying torques to the various hinges.',
    
    'Swimmer-v4':'The task is a reinforcement learning problem where an agent controls a 2-dimensional figure consisting of a torso at the top and a tail at the bottom. The action space consists of 2 continuous values, each between -1 and 1, representing the torque applied at one hinge joints: {{0: the torso rotor, 1: the tail rotor}}. The goal is to make the figure swim forward (right) by applying torque to the two hinges that connect the torso and tail.',

    'Walker2d-v4':'The task is a reinforcement learning problem where an agent controls a 2-dimensional bipedal robot consisting of seven main body parts - a single torso at the top (with the two legs splitting after the torso), two thighs in the middle below the torso, two legs below the thighs, and two feet attached to the legs on which the entire body rests. The action space consists of 6 continuous values, each represents the torque applied at one hinge joints: {{0: the right thigh rotor, 1: the right leg rotor, 2: the right foot rotor, 3: the left thigh rotor, 4: the left leg rotor, 5: the left foot rotor}}. The goal is to make the robot walk forward (right) by applying torque to the six hinges that connect the seven body parts.',
}

env_describe_name = {
    'Ant-v4': 'The task is the Ant-v4 control in MuJoCo environments.',

    'HalfCheetah-v4':'The task is the HalfCheetah-v4 control in MuJoCo environments.',
    
    'Hopper-v4':'The task is the Hopper-v4 control in MuJoCo environments.',
    
    'Humanoid-v4':'The task is the Humanoid-v4 control in MuJoCo environments.',

    'Swimmer-v4':'The task is the Swimmer-v4 control in MuJoCo environments.',
    
    'Walker2d-v4':'The task is the Walker2d-v4 control in MuJoCo environments.',
}